### ISSUE TITLE
Move CC labs website to GitHub

### ISSUE THREAD

**Issue by mattl** [creativecommons/labs#3]
It's mostly in this repo anyway. We probably need to mostly just make this a gh-pages branch and then move over the broken stuff.

@peterspdx notes that the following are broken/missing:

http://labs.creativecommons.org/2011/ccrel-guide/
http://labs.creativecommons.org/2011/ccrel-guide/examples/pdm.html

Don't worry, we have all the old files somewhere ;)

**Comment by peterspdx** [comment]
would love a snapshot of the CC0 deed showing copy/paste attribution, unable to locate that but will keep looking.

**Comment by peterspdx** [comment]
of course, as soon as I ask and give search one last attempt, I found it.  attached here.
![screen shot 2015-05-13 at 8 53 04 am](https://cloud.githubusercontent.com/assets/6127036/7614735/965aef06-f94d-11e4-9e9e-582fd9f13ef7.png)

**Comment by mattl** [comment]
Can you paste that URL in here, so we can make sure to bring it over?

**Comment by peterspdx** [comment]
all I have is the screenshot.  It was an attachment to an email that I found, but was in .tiff format (github doesn't support that) so I took a screenshot of the .tiff file :-/

**Comment by peterspdx** [comment]
...I don't know how to make the wavy line or else I'd try to see if I could get to it based on the screenshot.  perhaps one of you smart tech people know how?

**Comment by mattl** [comment]
Ah, okay. I'll root around, see if we can find Nathan's old files.



---
Matt Lee
Creative Commons
Boston, MA, USA

**Comment by mattl** [comment]
https://github.com/creativecommons/labs/issues/4

**Comment by robmyers** [comment]
Added .gitmodules to restore missing ccrel-guide files, and also directories under /demos.

I'm not sure about all the /demos submodules, I've matched names as best I can.

@mattl: rehost labs.creativecommons.org here, or forward here somehow? If the latter, how?

**Comment by mattl** [comment]
Let's move demos, etc to a demos branch. I'll redirect the rest.

**Comment by robmyers** [comment]
Cool. Closing.

**Comment by mattl** [comment]
Let's get the demos up and working first....  

http://labs.creativecommons.org/blog/ should redirect for you now.

**Comment by robmyers** [comment]
Demos is a nest of submodules. As we didn't have .gitmodules I don't know what they were originally (I couldn't match the existing commit hashes to anything). So I added whatever seemed defensible. Some of them include php code, which won't fly on Github.

**Comment by robmyers** [comment]
How should we proceed with demos?

**Comment by mattl** [comment]
Put demos in their own branch, no submodules.

---
Matt Lee
Creative Commons
Boston, MA, USA

**Comment by robmyers** [comment]
New branch: inline repos, nuke modules & .git files in dirs.

Makefile for redirects on labs. Put on branch. Include qdp as part of that.
