### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by farfallosa** [creativecommons/labs#5]
Is the concept of the three layers (legal code, human user, machine readable) still valid?

**Comment by robmyers** [comment]
We still present the licenses in this way and recommend that people use them in this way.

Machine-readable licenses haven't caught on as much as I think we originally hoped but projects like Google's recent machine learning CC-BY image set show the value of making it easy for software to process licensing information.

Out of interest, if you were to propose different (or no) layers, how would you recommend we structure them now?

**Comment by kgodey** [comment]
I'm closing this since there don't seem to be any open questions here. Feel free to reopen if needed.
